#
# Module manifest for module 'SecretManagement.HashiCorp.HCP.Vault.Secrets'
#
# Generated by: erikgraa
#
# Generated on: 05/20/2025
#

@{
    ModuleVersion = '0.2505.1'
    CompatiblePSEditions = @('Core', 'Desktop')
    GUID = '94214630-d2e7-4a06-8b47-e7302dd8c69b'
    Author = 'erikgraa'
    Copyright = 'Copyright (c) 2025 erikgraa, licensed under the MIT License.'
    Description = 'A SecretManagement Vault extension for HashiCorp HCP Vault Secrets.'
    PowerShellVersion = '5.1'

    NestedModules = @('./SecretManagement.HashiCorp.HCP.Vault.Secrets.Extension')

    RequiredModules = @('Microsoft.PowerShell.SecretManagement')

    PrivateData = @{
        PSData = @{
            Tags = @(
                'HashiCorp', 'HCP', 'PowerShell', 'PowerShell-Core', 'Secret',
                'Secrets', 'SecretManagement', 'Vault', 'VaultExtension', 'Microsoft'
            )

            ProjectUri     = 'https://github.com/erikgraa/SecretManagement.HashiCorp.HCP.Vault.Secrets'
            License        = 'https://github.com/erikgraa/SecretManagement.HashiCorp.HCP.Vault.Secrets/blob/main/LICENSE'
            IconUri        = 'https://raw.githubusercontent.com/erikgraa/SecretManagement.HashiCorp.HCP.Vault.Secrets/refs/heads/main/images/logo.png'
            ReleaseNotes   = 'https://github.com/erikgraa/SecretManagement.HashiCorp.HCP.Vault.Secrets'
        }
    }
}